#server:
#  port: 8083
spring:
  application:
    name: IMAGE-SERVICE
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost    
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/
  server:
    waitTimeInMsWhenSyncEmpty: 0